id: P009192
initial_creation_type: ocr
source_metadata:
  id: bdr:W23615
  title: ཞབས་དྲུང་དག་སྣང་མའི་སྐོར།
  author: ''
  volumes:
    504160c9db88497ca774c3476109e5fe:
      image_group_id: I1KG16723
      title: ''
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
