id: IFF481988
legacy_id: P009192
ocr_import_info:
  bdrc_scan_id: W23615
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T20:49:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:18:59.756118+00:00'
last_modified: 2022-09-02 09:19:15.013856
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23615
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23615
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞབས་དྲུང་དག་སྣང་མའི་སྐོར།
  author: གསེར་ཀོང་ངག་དབང་ཚུལ་ཁྲིམས་དོན་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.8315921243403948
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I1KG16723:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16723
      total_pages: 274
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16723.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8315921243403948
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
